### ISSUE TITLE
Hello World example

### ISSUE THREAD

**Issue by doyouevennodebro** [joshmanders/node-by-example#3]
While attempting to provide a simple answer, this is objectively wrong.  We can go through the document line by line to point out the errors.

Problem 1:

    Line 1: console.log(`Hello World`)

See Issue #2, Without a semicolon, a new user (the only people interested in such an example) will find that their code  fails all linters.  Even if not required for the v8 engine to parse the js file, understanding how the underlying engine parses, and when semicolons are or are not required, is advanced javascript. 

Problem  2: 

     Line 1: console.log(`Hello World`)

See Issue #2,  Upon review of the same line again, assuming we added a semi-colon, we will still fail linters.  The string being used is surrounded by back ticks as opposed to single quotes.  Back ticks are used to format template literals as a part of ES6/ES2015. This is only supported in modern versions of node (which should be clearly noted), and as such, should be noted as this article is directed towards the most basic of users.  

Problem 3

     Line 1: console.log(`Hello World`);

Assuming that the user has added a semi-colon, and installed a modern version of node, this will still fail linters as, once again, this is written using an ES6/ES2015 template literal.  As such, all javascript files written in ES6/ES2015, should have a global `'use strict';` declared at the beginning of each file.  To note: `'use strict';` includes a semi-colon at the end of the line (see Problem 1).

Thanks.
-doyouevennodebro

**Comment by joshmanders** [comment]
Thank you for pointing that out @doyouevennodebro and I have actually just pushed a style guide that will address all those issues. 

https://github.com/joshmanders/node-by-example/blob/master/CONTRIBUTING.md#style-guide

The semicolon missing is a mindframe of my own projects, but we're opting for being very conservative with the style guide so that we do not put pressure on the users having to understand ASI and how it works, therefore I will be fixing the missing semicolon there.

Regarding modern Node versions, in an attempt to curb the examples from going stale, we're opting to require all examples to implement modern ECMASCript features that are available in the current LTS version of Node.
