### ISSUE TITLE
'it's the bare minimum to getting you started in Node.js'

### ISSUE THREAD

**Issue by doyouevennodebro** [joshmanders/node-by-example#7]
The Novice example, "Hello World" states that:

"it's the bare minimum to getting you started in Node.js"

It could (and should be argued) that, at a bare minimum, novice node users should understand some of the basics of javascript, including syntax and primitives.

Reference:

    'use strict';

    const doYou = 'no';
    const doYouEvenNodeBro = () => doYou;

Given the example, a novice user would have a difficult time ascertaining that the `const`s being used are of a significantly different nature.

Thanks.
-doyouevennodebro

**Comment by joshmanders** [comment]
Since this is more geared towards Node and not JavaScript as a whole, I'd like to assert that users understand the basic concepts of JavaScript. 

Take the Hello World example, if they didn't understand the basic concepts, then we'd have to go more in depth on what the `console` object is, what does `log` do, etc. But with Node, they just need to know the differences between them, hence why we link to the Node.js API docs on `console` and not Mozilla Developer Network or something.

**Comment by doyouevennodebro** [comment]
Perhaps lacking from most documentation, and what should be added to this then, is a statement or (since this is educational) a few links describing an expectation of prior knowledge/understanding before jumping into further edification via this community.

**Comment by joshmanders** [comment]
Agreed.

**Comment by joshmanders** [comment]
This has been covered on the front of the site now.
